---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.example.com
  resources:
  - websiteoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.example.com
  resources:
  - websiteoperators/finalizers
  verbs:
  - update
- apiGroups:
  - operator.example.com
  resources:
  - websiteoperators/status
  verbs:
  - get
  - patch
  - update
