# permissions for end users to edit websiteoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: websiteoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: website-operator
    app.kubernetes.io/part-of: website-operator
    app.kubernetes.io/managed-by: kustomize
  name: websiteoperator-editor-role
rules:
- apiGroups:
  - operator.example.com
  resources:
  - websiteoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.example.com
  resources:
  - websiteoperators/status
  verbs:
  - get
